version: "3"
services:
  web:
    container_name: web
    build: .
    restart: always
    volumes:
      - .:/fresh-bytes

  
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env