version: "3"
services:
  web:
    container_name: web
    build: .
    restart: always
    ports: 
      - 5001:5000
    volumes:
      - .:/fresh-bytes
    ports: 
      - 5001:5000

  
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env